### ISSUE TITLE
Comments are not colored (not grayed out).

### ISSUE THREAD

**Issue by trusktr** [hughsk/language-glsl#13]
For reference:

``` glsl
// this is a comment, and you can see the variable "gl_Layer" is highlighted.
void main(void) {
}
```

Actual:
![screen shot 2016-07-18 at 5 38 00 pm](https://cloud.githubusercontent.com/assets/297678/16934759/6b9953a0-4d0e-11e6-932b-ca8bb1d2923b.png)

**Comment by trusktr** [comment]
Is this a bug, or just not implemented yet?

**Comment by fordhurley** [comment]
Looks like a bug to me. Thanks for reporting.

**Comment by fordhurley** [comment]
Just checked and this seems to have been fixed:

<img width="748" alt="screen shot 2017-10-29 at 11 09 01 am" src="https://user-images.githubusercontent.com/200646/32145121-9a89628a-bc99-11e7-8246-83a68475a517.png">
