### ISSUE TITLE
idea: GLSL`..` string template for highlight inline in JS

### ISSUE THREAD

**Issue by gre** [hughsk/language-glsl#16]
https://github.com/gandm/language-babel/issues/242#issuecomment-255997024

what do you think of this idea?

I would like to be able to write a 
```
GLSL`
...
`
```

block and have glsl highlight in it.

`GLSL` would just be a function that gives back the templated string, but later we could imagine a proprocessor a-la-Relay.QL ;)

**Comment by gre** [comment]
don't worry, it's possible already!
https://github.com/gandm/language-babel/issues/242#issuecomment-256016824

**Comment by EloB** [comment]
@gre Does this still work because when I use it it never highlights...?

![image](https://user-images.githubusercontent.com/476567/72471168-62ec2080-37e2-11ea-9365-957a534be510.png)
![image](https://user-images.githubusercontent.com/476567/72471204-739c9680-37e2-11ea-8099-8381150a6c1f.png)
