### ISSUE TITLE
Why is "double" an illegal type?

### ISSUE THREAD

**Issue by Sogomn** [hughsk/language-glsl#22]
GLSL definitely has the double precision float. Why would it be marked as illegal?

**Comment by fordhurley** [comment]
You're right, it is documented here: https://www.khronos.org/opengl/wiki/Data_Type_(GLSL)

I also don't see the `dmat` (double precision matrix) types recognized by the grammar either. I believe all of these double types were added in OpenGL 4, so the grammar is likely just lagging behind.

**Comment by fordhurley** [comment]
Fixed by #11.
