### ISSUE TITLE
Package.loadSettings is deprecated.

### ISSUE THREAD

**Issue by kirbasin** [hughsk/language-glsl#5]
Store package settings files in the `settings/` directory instead of `scoped-properties/`
```
Package.loadSettings (/Applications/Atom.app/Contents/Resources/app/src/package.js:565:9)
<unknown> (/Applications/Atom.app/Contents/Resources/app/src/package.js:187:43)
```

**Comment by hughsk** [comment]
I'm not sure how this is related to this package – could you please elaborate? Thanks :)

**Comment by kirbasin** [comment]
Seems like Atom changed around some APIs, this is the message I get in 0.189.0 version for your package, it suggested to create this GitHub issue for me :)

**Comment by hughsk** [comment]
Ahhh gotcha. Thanks for the heads up, fixed! :)
